// const nodemailer = require('nodemailer');
// require('dotenv').config(); // Load environment variables

// // Create the transporter
// const transporter = nodemailer.createTransport({
//   service: 'gmail',
//   auth: {
//     user: process.env.EMAIL_USER, // Use the email from .env
//     pass: process.env.EMAIL_PASS    // Use the app password from .env
//   }
// });

// // Function to send login alert email
// const sendLoginAlert = async (userEmail, userName) => {
//   const mailOptions = {
//     from: process.env.EMAIL_USER,
//     to: userEmail,
//     subject: 'Login Alert',
//     text: `Hello ${userName},\n\nThere was a login to your account. If this wasn't you, please secure your account immediately.\n\nRegards,\nYour Team`,
//     // Optionally, you can add an HTML body
//     // html: `<p>Hello ${userName},</p><p>There was a login to your account. If this wasn't you, please secure your account immediately.</p><p>Regards,<br>Your Team</p>`
//   };

//   try {
//     await transporter.sendMail(mailOptions);
//     console.log(`Login alert sent to ${userEmail}`);
//   } catch (error) {
//     console.error('Error sending email:', error);
//   }
// };

// module.exports = sendLoginAlert;




// new one

// const nodemailer = require('nodemailer');

// // Create the transporter with the necessary SMTP details
// const transporter = nodemailer.createTransport({
//     secure: true,
//     host: 'smtp.gmail.com',
//     port: 465,
//     auth: {
//         user: 'skin.ai2024@gmail.com',    // Your Gmail email address
//         pass: 'your-app-password'         // Replace with App Password generated by Google
//     }
// });

// // Function to send email
// function sendEmail(to, sub, msg) {
//     transporter.sendMail({
//         from: 'skin.ai2024@gmail.com',  // Sender address
//         to: to,                         // Recipient email address
//         subject: sub,                   // Email subject
//         html: msg                       // Email content (can be HTML)
//     }, (error, info) => {
//         if (error) {
//             console.log('Error occurred: ', error);
//         } else {
//             console.log('Email Sent: ', info.messageId);
//         }
//     });
// }

// // Example usage of sendEmail function
// sendEmail('recipient@example.com', 'This is SUBJECT', '<h1>This is the email content</h1>');
